name: "build-test"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: retrieve some info
        uses: ./
        with:
          deployment-url: https://action-vercel-deployment-info-kvmlvnbln-boredland.vercel.app
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
