name: "build-test"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4
      - name: retrieve some info
        uses: ./
        with:
          deployment-url: https://action-vercel-deployment-info-kvmlvnbln-boredland.vercel.app
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
