name: "build-test"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
      - name: retrieve some info
        uses: ./
        with:
          deployment-url: https://action-vercel-deployment-info-kvmlvnbln-boredland.vercel.app
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
