name: "build-test"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - name: retrieve some info
        uses: ./
        with:
          deployment-url: https://action-vercel-deployment-info-kvmlvnbln-boredland.vercel.app
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
