name: "build-test"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - name: retrieve some info
        uses: ./
        with:
          deployment-url: https://action-vercel-deployment-info-kvmlvnbln-boredland.vercel.app
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
